default: &default
  _secure_geocoder_lookup_app_id: IxQxXVLOChkhRGXWANMNMZ2OZIikmY07e7m2NAVikm3l7B9swS7vu17p1nH2ETt8V+22KPb01djVqZxmP6TQhzMyBoZOUW1OEXm3QKvqGj2e/N9j2rNKJzZH1tUwl85f2BwQ0pVgpXHO8DgmYTNVxaSNGz60UQb9S9n1SiySHZmKyEBdtUg5IY4ffjlAwONCvfSvKGoMueICmh6XAWOBQzuvpmYSUADJLyufVZNvU4mmEMH6p0u4GtalEaB/kukYnAYtG8aGBXB8T47GWJM/pF/TPnA54EM8F2cM0A0dV7ToC1BOJxGxZhluYSEzuNnPKjgQ2uqb4bIGrxaYv9fF2w==
  _secure_geocoder_lookup_app_code: UEmKQQOo/KHbQn6OgJMlLU96E5TwnXMqvaYGjAviz3f/cRs6osWL86StOrw3mNHKnqArnLVqukPjYi5nzBvzUrDQ7orvQPWFDUUD0SXIwdX2A1QK8vkhzOLFJ520wZZ8Oomyz8PBroFedE/Twp4N1oBUfkGyivhBQcxGs2uFckuzvUyPMypf3ZHdsgJ0Yslpqjlvzyl/G6GH4ZFbwYDQRie3Kg49GtOWf1iyfda4pBrtwwY18umoR55VOs12Dp+GAOFL+cCz/5nrptmTUrrSqNvfy8gUpfjYwTDZdy07cYm5XFVgxCg+Fb6fyxPmnEKg8nTil0BlHzzxLsPwK+/z0g==

  smtp:
    _secure_username:
    _secure_password:
    _secure_address: Iqw6vBOklItkK2NXflP/aZ1zuQuPvQsv8r8wexJrb5k8yG7QSwFUR1FyUN2LTxgZBsVZVJHpybbIgkVJoR2Zrr3UfwAGlsN6UmDk+Ccp/lKEePPVFx1o5Mzzw0vG3AulPe4K1Jwxp3Fcw/pbgmPRIGOL0fxjVX+LdgQfTBwE18VPIbsB3NACJsy05nXuu33F2niiZPNfrBJZ1zteNpWXvxOAEDTlYTc1893PqlNToOAOvIzNaQ+ZeJtClmrchC6z/GiOc72HzfizMiHzHmiQahCbQix+y3NyOw6oNmlt38uWD5Nkmk6eTjsnoNhlF9fFUB9/o5QHxD8r5x0KxZppCw==
    _secure_domain: VWfuMblUDD8y/quUDfFW44k5qjgZDt5uSfQTphcHyFHAQf+3VcDz40z6Zf0CcU12sdA/oQO3meCuOirxjoi9NFLHPLtrxV65sE+cukNyhNvc4ru7Uh02LLpTHp6thxp12/9nkRpym4PjGgQZjwsr0F2aNRPkiGOasLhMRu3XGiR+rVTc+hWyWmKYTIMqdWqjrQ++v8jJH9X9Caw7lbVtevXbD5ApwvbJD5txCNt9qYneOsruVyqw84QdHbQ4QqKuP+S3oT5yzzzETsfbMBApIio6Z7rPrkLnpA/rQLeKxJ8mCKiOMmKr8nlkb70QG6aOl9gbqA1GgaQKSngWb/2OnA==
    _secure_port: 25

  _secure_secret_key_base: fTsKZRPt9waZ4qzxWl8Og4GwWIEOL4weA6B8iFy6c/nXqQ956cycig5sn45eQQNB4V+8w4WxjG457VhrqKSIKWCWD+rjYAs17akdSy8ytfl7BdO1h2LzDPMq9y+oElljilwQ6M3czWqJ7JwCeSe0twhzNJxYYXG7DLccLr1H4m1MF0bisUUxs8i7BaKu+jG27j42RmxE+tXB+R+E5eqnyodIK1Dey4GoqpYFFJBv7MnypX060DekxtwMisyJT/cjmYWmsSkXripjJVTUPULjmlmVp6n+xLnTfIdsHyEitbgtsVZp4cmVKGkL3xTcov5tTELuOQpjkHCg1xt/UpBelg==#oqkfsfkYS+CQXvJXA+KqqA==#T/p3ACcDkIleAUZ0/O1kr0exkAPFptyA2PxSA0LY7hn3FN/+Wi6X82GWOdEL0b8Hbz1q08Oktfgv8+lZnDjBWfRGlTJIR5uWKhpJOY018v1cTMtYw+4H7OsAPx3O8FX3aB/V7U4e7+EZAsqqC3LyD7ZEmaMBSisa6Ix0SLxqZIYUiLjZ7umOcRnt7V2DCUCS

  imipre:
    _secure_client_id: PKw3XLrioBVJApwS4ufTigC4URc1RzppkyGtQ61O6wfGwp46TwpcFxTSJCl9da8l5VAaKWDt50jtcnNdaMxbY0N+7m9QQgBeZI45YR2p/ocaYN6p4PaMrcVmqdfdCaZNIymE4YrY53at0vj+AMW3CEhOJgG/Igf8umiV5cq/4QkrUtyxCOd6EDeEbTmYpj7Vbj6Fbl93Hu5pXMYzH9N3eaZwyerZarz4NTmSksX5nyOYL610nKbEga8bv5gG1gTyRRZufYx/PKnsxM4M6T79db4S300SJT9e1Drw3T7gWGfpvW9V+40hDrfRNVZ4HRoFUfRc2+/wwA63wik905PVNQ==
    _secure_client_secret: ESgQEWB1Cv/twXLjrzBdtYoBvRu1H2nm8khNkWY3ta6tAVRNcI816jgojwbdVEB+ryU3d/8WFDyHeicZITzcC6Uc4DTLf4GRZppO6ICLyGnUdXWDQL8FnVJRL+HZ/ditWJXD9AdbuknE6djXM84m+1D79Y3LG4DjP+I0Ys8SBz+sV5hWmwaHyfQ6u84F+kg87WAX/EOQQ3SnSEVRiTDOd4Tf3s4vCU5n15x7oeymGVD683UBYyDam0ZOQTT5GB0IuG0ciOLUIk3pt8oEPJXv6EodPKSgVJW3MUK0/lAQTDu7TQpjtdErl34aT8CNZpasJh11h2KAXEp1ph78JSKGww==
    domain: IMIPRE
    scope: IMI_BASIC_PRE.Info
    site: https://appspre.ajuntament.bcn
    redirect_uri: https:///decidim-pre.ajuntament.bcn/users/auth/imipre/callback
    info_url: https://appspre.ajuntament.bcn/oauth2/rest/token/info?access_token=

development:
  <<: *default
  secret_key_base: 4de720903a5d5f54094210f69423493dfdc56413a42907f7684766bff965695c0deec064fc03eff5c1e34fff618f70bdcac7127d853d6a0e5a4c48ccc267f2ad
test:
  <<: *default
  secret_key_base: 8d0e722712908c69c5005aefe275472ba3eae7fe30f982155dcd816896155f7e3848223af932c530de9baf0f22af45a9f15e64a7af315f99d0a5bb1e48c1e332
production:
  <<: *default
