# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  omniauth:
    facebook:
      # It must be a boolean. Remember ENV variables doesn't support booleans.
      enabled: false
      app_id: <%= ENV["OMNIAUTH_FACEBOOK_APP_ID"] %>
      app_secret: <%= ENV["OMNIAUTH_FACEBOOK_APP_SECRET"] %>
    twitter:
      enabled: false
      api_key: <%= ENV["OMNIAUTH_TWITTER_API_KEY"] %>
      api_secret: <%= ENV["OMNIAUTH_TWITTER_API_SECRET"] %>
    google_oauth2:
      enabled: false
      client_id: <%= ENV["OMNIAUTH_GOOGLE_CLIENT_ID"] %>
      client_secret: <%= ENV["OMNIAUTH_GOOGLE_CLIENT_SECRET"] %>
    imipre:
      enabled: false
      client_id: <%= ENV["IMIPRE_CLIENT_ID"] %>
      client_secret: <%= ENV["IMIPRE_CLIENT_SECRET"] %>
      info_url: <%= ENV["IMIPRE_INFO_URL"] %>
      redirect_uri: <%= ENV["IMIPRE_REDIRECT_URI"] %>
      site_url: <%= ENV["IMIPRE_SITE_URL"] %>
      scope: <%= ENV["IMIPRE_SCOPE"] %>
      domain: <%= ENV["IMIPRE_DOMAIN"] %>
      icon_path: Oauth_logo.svg
    saml:
      enabled: true
      idp_cert: <%= ENV["SAML_IDP_CERT"] %>
      idp_sso_target_url: <%= ENV["SAML_IDP_SSO_TARGET_URL"] %>
      sp_entity_id: <%= ENV["SAML_SP_ENTITY_ID"] %>
      strategy_class: <%= ENV["SAML_STRATEGY_CLASS"] || OmniAuth::Strategies::SAML %>
      attribute_statements:
        email:
          - mail
        name:
          - givenName
          - nom
      certificate: <%= ENV["SAML_CERTIFICATE"] %>
      private_key: <%= ENV["SAML_PRIVATE_KEY"] %>
      user_types: <%= ENV["SAML_USER_TYPES"] || %w[T1 T2 T3 T11] %>
      cn: <%= ENV["SAML_CN"] || "ACCES" %>
      security:
        authn_requests_signed: <%= ENV["SAML_SECURITY_AUTHN_REQUESTS_SIGNED"] || true %>
        signature_method: <%= ENV["SAML_SECURITY_SIGNATURE_METHOD"] || XMLSecurity::Document::RSA_SHA256 %>
  maps:
    api_key: <%= ENV["MAPS_API_KEY"] %>

development:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || "b909b44627fbb3d4a30323d3bfce412ee5f4c69777276e041da0ab00d68431d6177905e7c1bf337daeee51fb528fb0cc47fc20e3c0a7957237a3c5d6710d79ce" %>
  omniauth:
    imipre:
      enabled: false
    saml:
      enabled: false
      idp_cert_fingerprint: <%= ENV["SAML_IDP_CERT_FINGERPRINT"] %>
      idp_sso_target_url: <%= ENV["SAML_IDP_SSO_TARGET_URL"] %>
  maps:
    api_key: 1234123412341234

test:
  <<: *default
  secret_key_base: 8162c8ea1b590d0322963eef63f5d279ef1bfcfc30dab49961fe80d8ced569eca4f8bbe8bf43c586be838a538c56039faca87556c50a958b9220f2b14a6f417f
  omniauth:
    facebook:
      enabled: true
    twitter:
      enabled: true
    google_oauth2:
      enabled: true
  maps:
    api_key: 1234123412341234

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  smtp_username: <%= ENV["SMTP_USERNAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>
  smtp_address: <%= ENV["SMTP_ADDRESS"] %>
  smtp_domain: <%= ENV["SMTP_DOMAIN"] %>
  smtp_port: <%= ENV["SMTP_PORT"] || "587" %>
  smtp_starttls_auto: false
  smtp_authentication: <%= ENV["SMTP_AUTHENTICATION"] || "plain" %>
