default: &default
  smtp:
    username:
    password:
    address: localhost
    domain: example.com
    port: 25

  imipre:
    domain: IMIPRE
    scope: IMI_BASIC_PRE.Info
    site: https://appspre.ajuntament.bcn
    redirect_uri: https://aytobarcelona-decidim.dev.aspgems.com/users/auth/imipre/callback

  maps:
    api_key: <%= ENV["MAPS_API_KEY"] %>

  saml:
    idp_sso_target_url: <%= ENV['IDP_SSO_TARGET_URL'] %>
    idp_cert: <%= ENV['IDP_CERT'] %>
    certificate: <%= ENV['CERTIFICATE'] %>
    private_key: <%= ENV['PRIVATE_KEY'] %>
    sp_entity_id: <%= ENV['SP_ENTITY_ID'] %>
    user_types: ['T1', 'T2', 'T3', 'T11']
    cn: 'ACCES'

development:
  <<: *default
  secret_key_base: 4de720903a5d5f54094210f69423493dfdc56413a42907f7684766bff965695c0deec064fc03eff5c1e34fff618f70bdcac7127d853d6a0e5a4c48ccc267f2ad
test:
  <<: *default
  secret_key_base: 8d0e722712908c69c5005aefe275472ba3eae7fe30f982155dcd816896155f7e3848223af932c530de9baf0f22af45a9f15e64a7af315f99d0a5bb1e48c1e332
production:
  <<: *default
  imipre:
    domain: IMIPRE
    scope: IMI_BASIC_PRE.Info
    site: https://appspre.ajuntament.bcn
    redirect_uri: https://aytobarcelona-decidim.dev.aspgems.com/users/auth/barcelona-rrhh/callback
    info_url: https://appspre.ajuntament.bcn/oauth2/rest/token/info?access_token=
