default: &default
  _secure_here_api_key: je/VLXgcb77uQ2QJtcETAqa5oAmrCOmle5pI4GOumYcBaUBjVj/7EzQmuye6VtXiiD67C1xCjNS8COPAf9RomqqR5KZQODRimrtgfEdMolEUCVaMS8M8my6ZJI35UQmlgvAne+x5g/6YukELO06X4KuEEIaO7jp4UBWsIsGxPYorO+1jbR4cUjvcGdGrO/0fS2QWdRRDJFFu48NH0/80e/KuakdDBa4vOZtb/GwOtlgMTRBk708m3vdxkh77Xyl3TY/lhAv7QWa624g0p/9MTPf4UY01ZptbRwUoZ4AVo5DaHQ1HT+J5x7XVOSl500az3YITylDRWAflsfj4gbqasw==

  smtp:
    _secure_username:
    _secure_password:
    _secure_address: SkTYUq4er+hm5P5951RwkXYZTIu/B7MWNyoTkRZUSH5HIOofugZRQ8R78nbqlQGr36oaWZplutoUi9a8dzRifFKtRVT8U5Mvla4YTOa5RB9XG7bwWrHR7DoaciSoZm8vrV/1a/q6MTLHC5n2e4r0t6mfD+72JUfQPhshQ7brEs7hYv2ORSM0U2WwriZkO+ABJzGsP921zmAE+EVUnSITOg/2YcFyC/duhQmxkKjsVkHWSv4zNqOW2hp0W1b4uh/QZdhzFP4FmUloFgaeQeWbhnSXsIDUp6ePxWddaBRqNoCUnhLR+NCPnu77B1pM1Qs4CMFNPTgipRgHkqBXv6ImpQ==
    _secure_domain: bt5cCs9AbJiXsjOJJSwTiqNQW2KAIGSR1sQY37dW+7QOV1oZ4rOjsXyNfQ5vbt5MEQ+w2lMC2Km+BekL8x/nOwDx8JQqAR+GIX79pRTr8aOysofv/yhGKXBvpRhxxlvucSyZ2hvIJuoK37nyyuveN1qZH6ocVBKBTptmOdydwyvJkbO/GJCy4vIWy+PBB+FKCRp0UlPfrThdFZlDMLbpzCbdKv/qno5VXZ30YeUhzTWfEq+2X/8pKxageuGg3TGyZOlBOuxBv7+QXBkeuKOzexU1fv1BKXQY3fetPZK6ONvxx/CKjU7NCp6cLLiXZks+19nTCRy4zrbhXCwrTcdJmw==
    _secure_port: 25

development:
  <<: *default
  secret_key_base: 4de720903a5d5f54094210f69423493dfdc56413a42907f7684766bff965695c0deec064fc03eff5c1e34fff618f70bdcac7127d853d6a0e5a4c48ccc267f2ad
test:
  <<: *default
  secret_key_base: 8d0e722712908c69c5005aefe275472ba3eae7fe30f982155dcd816896155f7e3848223af932c530de9baf0f22af45a9f15e64a7af315f99d0a5bb1e48c1e332
production:
  <<: *default
  _secure_secret_key_base: fs55LjONItwaJFJIPG8hgHBl1uUNxb5TPRUk1WJOLiBnisNFuE9GGSyUs7gdt3531ndG5NICeFPyb4sPV60PEAvTzhTFaT08qeYcr6JcbLXJakNhh9sMLqd9wDM7Kzwv5Or3DHeCa/k7y4gS61jeK3ewhbE25Sy6OmJqSIR3cdNlYMLN4U4WawWRkrmXkpk5Qf4J4OtujgXxlk3Kd57HcJuwg/E/bdP2XnYDWmA6XnZlwDQ9arvIqI2prI53ypsWpg3GRn2kzL2a1ZDKayCADbRnfoHPaukkQKxDBIiR20SF8ID7joaZrMqb3kKA5umYGtPtSBcQKvFvVeligbDyeg==#g/4pyruAcaAU5B2I4y5Ghg==#gTCfJRl7xiYqKHDkVceFpr2nyGkMZZtolr93RToV9j5B19XNq/SZ5rrnMR3aub+LZlFONkTyk9XIZKGFaAgydgjuX/diOZVcTdkyyWGZz9uTOnaT5hHm9K2+2ab1rQ3dEPhHJCiA4RcKtUM3zlO/D2KT1Z4PcmvzSy6SG0CKlQ2guHmNz3HoAeUY4cIH0lXG
